config/routes.rb
Rails.application.routes.draw do

  root 'home#index'

  resources :blogs

end

app/models/blog.rb
class Blog < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  def new
    @blog = Blog.new
  end
  
  def create
    @blog = Blog.create blog_params
    redirect_to root_path
  end

private
  def blog_params
    params.require(:blog).permit(
      :title,
      :date,
      :content,
    )

  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @blogs = Blog.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :date %>
  <%= f.date_select :date, :start_year => 2014, :end_year => Date.today.year %>
  <br>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <br>
  <%= f.submit %>
<% end %>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form' %>

app/views/home/index.html.erb
<h1>Hello World</h1>

<%= link_to "New Blog", new_blog_path %>

<% @blogs.each do |blog| %>
  <br>
  <%= blog.title %>
  <br>
  <%= blog.date %>
  <br>
  <%= blog.content %>
  <br>
<% end %>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>